from __future__ import annotations


class MetricColumns:
    TR: str = "tr"
    PORTFOLIO_TR: str = "portfolio_tr"
    MDD: str = "mdd"
    ANNUAL_SR: str = "annual_sr"
    DAILY_CR: str = "daily_cr"
    DAILY_VOL: str = "daily_vol"
    DAILY_SOR: str = "daily_SoR"
    DOWNSIDE_DEVIATION_DAILY: str = "downside_deviation_daily"
    REQUIRED_MONEY: str = "required_money"
    TRIAL_ID: str = "trial_id"
    NUM_CONTRACTS: str = "num_contracts"
    CONTRACT: str = "contract"
    DF_PATH: str = "df_path"
    DF_LENGTH: str = "df_length"
    REWARD_SUM: str = "reward_sum"
    REWARD_MAX: str = "reward_max"
    NORMALIZED_REWARD: str = "normalized_reward"
    TRANS_REWARD_MEAN: str = "trans_reward_mean"
    TRANS_REWARD_STD: str = "trans_reward_std"
    TURNOVER: str = "turnover"
    MEAN_TURNOVER: str = "mean_turnover"
    MEAN_POSITION: str = "mean_position"
    MEAN_ABS_POSITION: str = "mean_abs_position"
    LONG_STEP_RATIO: str = "long_step_ratio"
    SHORT_STEP_RATIO: str = "short_step_ratio"
    FLAT_STEP_RATIO: str = "flat_step_ratio"
    RETURN_RATE: str = "return_rate"
    SCORE: str = "score"
    REQUIRE_MONEY: str = "require_money"
    SOURCE_FILE: str = "source_file"
    ROWS: str = "rows"
    INDICATOR: str = "indicator"
