[pytest]
filterwarnings =
    ignore:'parseString' deprecated.*:DeprecationWarning:matplotlib\._fontconfig_pattern
    ignore:'resetCache' deprecated.*:DeprecationWarning:matplotlib\._fontconfig_pattern
    ignore:'enablePackrat' deprecated.*:DeprecationWarning:matplotlib\._mathtext
    ignore:h5py not installed, hdf5 features will not be supported.*:UserWarning:tslearn\.bases\.bases
